"""Pydantic data models shared across the SDK (not env-var config).

These are *runtime* models used to pass structured data between modules,
distinct from the env-var ``Settings`` in ``env.py``.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class LLMRole(str, Enum):
    """The four LLM roles understood by the SDK."""

    QUICK = "quick"
    CODING = "coding"
    REASONING = "reasoning"
    MULTIMODAL = "multimodal"


class TaskContext(BaseModel):
    """Runtime context attached to a single Agent task execution."""

    task_id: str = Field(description="Unique task identifier (from task scheduler).")
    message_id: str = Field(description="Business message ID from the calling system.")
    session_id: str = Field(description="Business session ID from the calling system.")
    user_id: str = Field(description="User who triggered the task.")
    thread_id: str = Field(description="LangGraph thread_id (auto-generated by gateway).")
    attachment_ids: list[str] = Field(default_factory=list, description="Uploaded file IDs.")
    extra: dict[str, Any] = Field(default_factory=dict, description="Any extra metadata.")


class TaskResult(BaseModel):
    """Result payload returned to the task scheduler after Agent completes."""

    task_id: str
    thread_id: str
    message_id: str
    status: str = Field(description="'completed' | 'interrupted' | 'failed'")
    result_attachment_ids: list[str] = Field(default_factory=list)
    summary: str = Field(default="", description="Short natural-language summary.")
    error: str | None = Field(default=None)
