-- e_commerce_demo.dws_enterprise_wide definition

CREATE TABLE `e_commerce_demo`.`dws_enterprise_wide` (
  `enterprise_id` varchar(50) NOT NULL COMMENT '企业ID',
  `data_year` int NOT NULL COMMENT '数据年份',
  `enterprise_name` varchar(200) DEFAULT NULL COMMENT '企业名称',
  `industry_code` varchar(30) DEFAULT NULL COMMENT '行业编码',
  `industry_name` varchar(100) DEFAULT NULL COMMENT '行业名称',
  `grid_id` varchar(30) DEFAULT NULL COMMENT '经营网格ID',
  `grid_name` varchar(50) DEFAULT NULL COMMENT '经营网格名称',
  `region_id` varchar(20) DEFAULT NULL COMMENT '区域ID',
  `region_name` varchar(100) DEFAULT NULL COMMENT '区域名称',
  `register_grid_id` varchar(30) DEFAULT NULL COMMENT '注册网格ID',
  `bus_adress` varchar(255) DEFAULT NULL COMMENT '经营地址',
  `reg_address` varchar(255) DEFAULT NULL COMMENT '注册地址',
  `poi_latitude` decimal(10,6) DEFAULT NULL COMMENT '企业POI纬度',
  `poi_longitude` decimal(10,6) DEFAULT NULL COMMENT '企业POI经度',
  `poi_adress` varchar(255) DEFAULT NULL COMMENT '企业POI地址',
  `annual_revenue_report` decimal(18,2) DEFAULT NULL COMMENT '企业申报营收',
  `tax_declared` decimal(18,2) DEFAULT NULL COMMENT '企业申报税额',
  `land_area_mu` decimal(10,4) DEFAULT NULL COMMENT '占地面积（亩）',
  `power_consumption` decimal(12,2) DEFAULT NULL COMMENT '年度用电量（千瓦时）',
  `water_consumption` decimal(12,2) DEFAULT NULL COMMENT '年度用水量（吨）',
  `logistics_heat_index` decimal(10,4) DEFAULT NULL COMMENT '所在网格的年度平均物流热力指数',
  `revenue_ai_inferred` decimal(18,2) DEFAULT NULL COMMENT 'AI推演营收',
  `tax_ai_inferred` decimal(18,2) DEFAULT NULL COMMENT 'AI推演税额',
  `tax_gap_ratio` decimal(10,4) DEFAULT NULL COMMENT '税负差异率',
  `risk_score` decimal(10,4) DEFAULT NULL COMMENT '企业风险分',
  `risk_level` varchar(20) DEFAULT NULL COMMENT '企业风险等级',
  `is_scale_enterprise` tinyint DEFAULT NULL COMMENT '规上企业标识',
  `is_high_tech` tinyint DEFAULT NULL COMMENT '高新企业标识',
  `high_level_talents` int DEFAULT NULL COMMENT '高层次人才数量',
  `patents_num` int DEFAULT NULL COMMENT '专利数量',
  `rd_intensity` decimal(8,4) DEFAULT NULL COMMENT '研发强度',
  `is_listed` tinyint DEFAULT NULL COMMENT '是否上市',
  `enterprise_level` varchar(10) DEFAULT NULL COMMENT '企业级别',
  `data_source` varchar(50) DEFAULT NULL COMMENT '数据来源',
  `location_reality` tinyint DEFAULT NULL COMMENT '位置真实性',
  `choose_who` varchar(100) DEFAULT NULL COMMENT '数据选择来源',
  `is_risk` tinyint(1) DEFAULT NULL COMMENT '是否风险企业 0-否 1-是',
  `invoice_issued_amount` decimal(15,2) DEFAULT NULL COMMENT '期内开票总额（万元）',
  `invoice_received_amount` decimal(15,2) DEFAULT NULL COMMENT '期内收票总额（万元）',
  `invoice_issued_count` int DEFAULT NULL COMMENT '开票份数',
  `invoice_item_variance_score` decimal(5,2) DEFAULT NULL COMMENT '进销项品目背离度评分',
  `peak_invoicing_ratio` decimal(5,4) DEFAULT NULL COMMENT '顶额开票占比',
  `chain_id` varchar(30) DEFAULT NULL COMMENT '产业链环节ID(企业表)',
  `chain_name` varchar(100) DEFAULT NULL COMMENT '产业链环节名称(企业表)',
  `upstream_chain_name` varchar(100) DEFAULT NULL COMMENT '上游环节名称',
  `downstream_chain_name` varchar(100) DEFAULT NULL COMMENT '下游环节名称',
  `is_leading` tinyint DEFAULT NULL COMMENT '是否龙头(链路表聚合)',
  `leading_levels` varchar(255) DEFAULT NULL COMMENT '龙头等级聚合',
  `max_influence_radius_km` decimal(10,2) DEFAULT NULL COMMENT '最大影响半径',
  `primary_asset_id` varchar(50) DEFAULT NULL COMMENT '主经营资产ID',
  `primary_asset_name` varchar(200) DEFAULT NULL COMMENT '主经营资产名称',
  `primary_asset_type` varchar(30) DEFAULT NULL COMMENT '主经营资产类型',
  `primary_asset_status` varchar(30) DEFAULT NULL COMMENT '主经营资产状态',
  `primary_asset_land_mu` decimal(18,4) DEFAULT NULL COMMENT '主经营资产占地(亩)',
  `primary_asset_floor_sqm` decimal(18,2) DEFAULT NULL COMMENT '主经营资产建面(平米)',
  `occupancy_asset_cnt` int DEFAULT NULL COMMENT '企业占用资产数',
  `occupancy_total_area_sqm` decimal(18,2) DEFAULT NULL COMMENT '企业占用面积汇总',
  `occupancy_active_cnt` int DEFAULT NULL COMMENT '当前有效合同数',
  `invoice_issued_amt_year` decimal(18,2) DEFAULT NULL COMMENT '当年开票额',
  `invoice_received_amt_year` decimal(18,2) DEFAULT NULL COMMENT '当年收票额',
  `invoice_issued_cnt_year` int DEFAULT NULL COMMENT '当年开票数',
  `invoice_received_cnt_year` int DEFAULT NULL COMMENT '当年收票数',
  `supplier_rel_cnt` int DEFAULT NULL COMMENT '作为供应方关系数',
  `buyer_rel_cnt` int DEFAULT NULL COMMENT '作为采购方关系数',
  `supplier_strength_sum` decimal(18,4) DEFAULT NULL COMMENT '供应方关系强度和',
  `buyer_strength_sum` decimal(18,4) DEFAULT NULL COMMENT '采购方关系强度和',
  `latest_judgment_time` datetime DEFAULT NULL COMMENT '最新风险研判时间',
  `latest_pattern_id` varchar(30) DEFAULT NULL COMMENT '最新风险模式ID',
  `latest_pattern_name` varchar(100) DEFAULT NULL COMMENT '最新风险模式名',
  `latest_risk_type_name` varchar(100) DEFAULT NULL COMMENT '最新风险类型',
  `latest_comprehensive_score` varchar(20) DEFAULT NULL COMMENT '最新综合评分',
  `latest_judgment_summary` text COMMENT '最新研判摘要',
  `etl_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '装载时间',
  PRIMARY KEY (`enterprise_id`,`data_year`),
  KEY `idx_grid_id` (`grid_id`),
  KEY `idx_region_id` (`region_id`),
  KEY `idx_risk_level` (`risk_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='企业大宽表';