-- e_commerce_demo.dws_grid_wide definition

CREATE TABLE `e_commerce_demo`.`dws_grid_wide` (
  `grid_id` varchar(30) NOT NULL COMMENT '网格ID',
  `data_year` int NOT NULL COMMENT '数据年份',
  `grid_code` varchar(20) DEFAULT NULL COMMENT '网格编码',
  `grid_name` varchar(50) DEFAULT NULL COMMENT '网格名称',
  `region_id` varchar(20) DEFAULT NULL COMMENT '区域ID',
  `region_name` varchar(100) DEFAULT NULL COMMENT '区域名称',
  `polygon` text COMMENT '网格边界坐标',
  `area_mu` decimal(12,4) DEFAULT NULL COMMENT '网格面积(亩)',
  `area_kilometer` decimal(12,4) DEFAULT NULL COMMENT '网格面积(平方公里)',
  `center_point` varchar(100) DEFAULT NULL COMMENT '中心点',
  `enterprise_cnt` int DEFAULT NULL COMMENT '企业数量',
  `scale_enterprise_cnt` int DEFAULT NULL COMMENT '规上企业数',
  `high_tech_cnt` int DEFAULT NULL COMMENT '高新企业数',
  `total_annual_revenue` decimal(18,2) DEFAULT NULL COMMENT '企业申报营收汇总',
  `total_tax_declared` decimal(18,2) DEFAULT NULL COMMENT '企业申报税额汇总',
  `avg_risk_score` decimal(10,4) DEFAULT NULL COMMENT '企业平均风险分',
  `high_risk_cnt` int DEFAULT NULL COMMENT '高风险企业数',
  `asset_cnt` int DEFAULT NULL COMMENT '资产数量',
  `occupied_asset_cnt` int DEFAULT NULL COMMENT '已占用资产数',
  `vacant_asset_cnt` int DEFAULT NULL COMMENT '空置资产数',
  `total_land_area_mu` decimal(18,4) DEFAULT NULL COMMENT '资产占地汇总(亩)',
  `total_floor_area_sqm` decimal(18,2) DEFAULT NULL COMMENT '资产建面汇总(平米)',
  `kpi_month_time` date DEFAULT NULL COMMENT 'KPI月份',
  `output_per_mu` decimal(18,4) DEFAULT NULL COMMENT '亩产效益',
  `vitality_idx` decimal(18,4) DEFAULT NULL COMMENT '综合活力指数',
  `weakness_tag` varchar(200) DEFAULT NULL COMMENT '活力短板',
  `iot_latest_date` date DEFAULT NULL COMMENT 'IoT最新日期',
  `human_flow_idx` decimal(18,4) DEFAULT NULL COMMENT '人流指数(日)',
  `traffic_flow_idx_day` decimal(18,4) DEFAULT NULL COMMENT '车流指数(日)',
  `night_light_idx_day` decimal(18,4) DEFAULT NULL COMMENT '夜间灯光指数(日)',
  `logistics_heat_idx_day` decimal(18,4) DEFAULT NULL COMMENT '物流热力指数(日)',
  `iot_month_time` date DEFAULT NULL COMMENT 'IoT月级日期',
  `people_flow_idx_month` decimal(18,4) DEFAULT NULL COMMENT '人流指数(月)',
  `traffic_flow_idx_month` decimal(18,4) DEFAULT NULL COMMENT '车流指数(月)',
  `logistics_idx_month` decimal(18,4) DEFAULT NULL COMMENT '物流指数(月)',
  `night_light_idx_month` decimal(18,4) DEFAULT NULL COMMENT '夜间灯光指数(月)',
  `risk_weight_month` decimal(10,4) DEFAULT NULL COMMENT '风险权重(月)',
  `etl_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '装载时间',
  PRIMARY KEY (`grid_id`,`data_year`),
  KEY `idx_region_id` (`region_id`),
  KEY `idx_grid_name` (`grid_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='网格大宽表';