-- e_commerce_demo.dws_industry_wide definition

CREATE TABLE `e_commerce_demo`.`dws_industry_wide` (
  `chain_id` varchar(30) NOT NULL COMMENT '产业链ID',
  `data_year` int NOT NULL COMMENT '数据年份',
  `chain_name` varchar(100) DEFAULT NULL COMMENT '产业链名称',
  `parent_chain_id` varchar(30) DEFAULT NULL COMMENT '父产业链ID',
  `parent_chain_name` varchar(100) DEFAULT NULL COMMENT '父产业链名称',
  `chain_level` int DEFAULT NULL COMMENT '产业链层级',
  `chain_description` text COMMENT '产业链描述',
  `node_cnt` int DEFAULT NULL COMMENT '环节节点数',
  `key_node_cnt` int DEFAULT NULL COMMENT '关键环节节点数',
  `enterprise_cnt` int DEFAULT NULL COMMENT '企业数',
  `scale_enterprise_cnt` int DEFAULT NULL COMMENT '规上企业数',
  `high_tech_cnt` int DEFAULT NULL COMMENT '高新企业数',
  `leading_enterprise_cnt` int DEFAULT NULL COMMENT '龙头企业数',
  `grid_cnt` int DEFAULT NULL COMMENT '覆盖网格数',
  `region_cnt` int DEFAULT NULL COMMENT '覆盖区域数',
  `total_annual_revenue` decimal(20,2) DEFAULT NULL COMMENT '申报营收汇总',
  `total_tax_declared` decimal(20,2) DEFAULT NULL COMMENT '申报税额汇总',
  `avg_risk_score` decimal(10,4) DEFAULT NULL COMMENT '平均风险分',
  `high_risk_cnt` int DEFAULT NULL COMMENT '高风险企业数',
  `invoice_issued_amt_year` decimal(20,2) DEFAULT NULL COMMENT '当年开票额',
  `invoice_received_amt_year` decimal(20,2) DEFAULT NULL COMMENT '当年收票额',
  `intra_chain_rel_cnt` int DEFAULT NULL COMMENT '链内供需关系数',
  `supplier_rel_out_cnt` int DEFAULT NULL COMMENT '对外供应关系数',
  `buyer_rel_out_cnt` int DEFAULT NULL COMMENT '对外采购关系数',
  `relation_strength_sum` decimal(20,4) DEFAULT NULL COMMENT '关系强度汇总',
  `latest_judgment_time` datetime DEFAULT NULL COMMENT '链内企业最新研判时间(最大)',
  `etl_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '装载时间',
  PRIMARY KEY (`chain_id`,`data_year`),
  KEY `idx_chain_name` (`chain_name`),
  KEY `idx_parent_chain_id` (`parent_chain_id`),
  KEY `idx_data_year` (`data_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='产业维度大宽表';