"""OntologyRepository Protocol — abstract interface for all ontology adapters.

Every adapter (Local, Remote, Milvus, pgvector, etc.) must implement this interface.
Return types use dict for now; typed domain models from datacloud_server.models
will replace dict signatures in a follow-up adapter update task.
"""

from __future__ import annotations

from typing import Protocol


class OntologyRepository(Protocol):
    """Repository Protocol - all Adapters must implement this interface."""

    # ── Scene ──
    def list_scenes(self, base_id: str) -> list[dict]: ...
    def get_scene(self, base_id: str, scene_id: str) -> dict | None: ...
    def query_scenes(self, base_id: str, keyword: str | None) -> list[dict]: ...
    def count_scenes(self, base_id: str, keyword: str | None) -> int: ...
    def get_scene_details(
        self,
        base_id: str,
        scene_id: str,
        *,
        view_code: str | None = None,
        object_code: str | None = None,
    ) -> dict: ...
    def query_ontologies_by_scene(
        self,
        base_id: str,
        scene_id: str,
        *,
        page: int = 1,
        page_size: int = 20,
        keyword: str | None = None,
    ) -> dict: ...

    # ── Object ──
    def get_objects(self, base_id: str, scene_id: str) -> list[dict]: ...
    def get_object_detail(self, base_id: str, scene_id: str, object_code: str) -> dict | None: ...
    def create_object(self, base_id: str, scene_id: str, obj_data: dict) -> dict: ...
    def update_object(self, base_id: str, scene_id: str, object_code: str, obj_data: dict) -> dict: ...
    def delete_object(self, base_id: str, scene_id: str, object_code: str) -> None: ...

    # ── View ──
    def get_views(self, base_id: str, scene_id: str) -> list[dict]: ...
    def get_view_detail(self, base_id: str, scene_id: str, view_code: str) -> dict | None: ...
    def create_view(self, base_id: str, scene_id: str, view_data: dict) -> dict: ...
    def update_view(self, base_id: str, scene_id: str, view_code: str, view_data: dict) -> dict: ...
    def delete_view(self, base_id: str, scene_id: str, view_code: str) -> None: ...

    # ── Relation ──
    def get_relations(self, base_id: str, scene_id: str) -> list[dict]: ...
    def get_relation_detail(self, base_id: str, scene_id: str, rel_code: str) -> dict | None: ...
    def create_relation(self, base_id: str, scene_id: str, rel_data: dict) -> dict: ...
    def update_relation(self, base_id: str, scene_id: str, rel_code: str, rel_data: dict) -> dict: ...
    def delete_relation(self, base_id: str, scene_id: str, rel_code: str) -> None: ...

    # ── Datasource ──
    def get_datasources(self, base_id: str, scene_id: str) -> list[dict]: ...
    def get_datasource_detail(self, base_id: str, scene_id: str, db_id: str) -> dict | None: ...
    def create_datasource(self, base_id: str, scene_id: str, ds_data: dict) -> dict: ...
    def delete_datasource(self, base_id: str, scene_id: str, db_id: str) -> None: ...

    # ── Action ──
    def get_actions(self, base_id: str, scene_id: str, object_code: str) -> list[dict]: ...
    def get_action_detail(
        self, base_id: str, scene_id: str, object_code: str, action_code: str
    ) -> dict | None: ...
    def create_action(
        self, base_id: str, scene_id: str, object_code: str, action_data: dict
    ) -> dict: ...
    def update_action(
        self, base_id: str, scene_id: str, object_code: str, action_code: str, action_data: dict
    ) -> dict: ...
    def delete_action(
        self, base_id: str, scene_id: str, object_code: str, action_code: str
    ) -> None: ...

    # ── Search & Graph ──
    def search_instances(self, base_id: str, query: dict) -> dict: ...
    def search_ontology(self, base_id: str, scene_id: str, request: dict) -> dict: ...
    def search_ontology_base(self, base_id: str, request: dict) -> dict: ...
    def graph_query(self, base_id: str, scene_id: str, query: dict) -> dict: ...
    def graph_path(self, base_id: str, scene_id: str, query: dict) -> dict: ...

    # ── OWL Import ──
    def import_owl(self, base_id: str, scene_id: str, zip_bytes: bytes) -> dict: ...
